name: template_engine
description: A Dart package to parse and render templates, using (nested) variables and custom tags.
version: 1.5.1
repository: https://github.com/domain-centric/template_engine

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  http: ^1.3.0
  petitparser: ^6.1.0
  recase: ^4.1.0
  xml: ^6.5.0
  yaml: ^3.1.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.1
  shouldly: ^0.5.0+1
  build_runner: ^2.4.15
  documentation_builder: ^1.0.0
  
