name: template_engine
description: A Dart library to parse and render templates.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  given_when_then_unit_test: ^0.2.0
  shouldly: ^0.5.0+1

dev_dependencies:
  flutter_lints: ^2.0.0